#! /bin/bash
#--------------------------------------------------------------
#  RunLawn
#  Jia-hui Ma
#  jma289
#  lab3
#  compiles and executes Lawn.java and deletes Lawn.class
#--------------------------------------------------------------
echo "compiling Lawn.java"
javac Lawn.java >& Lawn-errs

echo "running Lawn.class"
java Lawn < Lawn-in > Lawn-out

echo "deleting Lawn.class"
rm Lawn.class

